### ISSUE TITLE
White line at top of profile

### ISSUE THREAD

**Issue by WnndGws** [ammgws/ammcon-frontend#13]
When I am logged into ammcon, when i click the hamburger to bring out the slider, at the top of the site there is a tiny white border. It drives me insane. Pls correct asap
![2017-03-03-16 42 40](https://cloud.githubusercontent.com/assets/10380089/23544110/8551d86e-0030-11e7-9f56-b5bebf7fe17e.png)

**Comment by ammgws** [comment]
Result of your #14 PR

![image](https://cloud.githubusercontent.com/assets/20397027/23575746/ceeb1e7c-00d5-11e7-909c-b060bebb3303.png)


NARP.

**Comment by WnndGws** [comment]
Cum

**Comment by ammgws** [comment]
Looks like the culprit is the CSS to do with this element (the most outer element for the side panel):
`<div data-role="panel" id="leftpanel" data-display="overlay" data-position-fixed="true">`

When page is loaded and panel is opened it has the following classes added to it, so have to look through them and see if there's anything there:
`<div data-role="panel" id="leftpanel" data-display="overlay" data-position-fixed="true" class="ui-panel ui-panel-position-left ui-panel-display-overlay ui-body-inherit ui-panel-fixed ui-panel-animate ui-panel-open">`

**Comment by ammgws** [comment]
Jquery mobile example with no white line:
`<div data-role="panel" id="defaultpanel" data-theme="b" class="ui-panel ui-panel-position-left ui-panel-display-reveal ui-body-b ui-panel-animate ui-panel-open">`

**Comment by ammgws** [comment]
Finally found it.

This CSS from nativedroid2.css setting top to 1px.:
```
.ui-panel-position-left > .ui-panel-inner {
    position: absolute;
    top: 1px;
    left: 0;
    right: 0;
    bottom: 0px;
    overflow: auto;
    -webkit-overflow-scrolling: touch;
}
```

Override it in ammcon.css:
```
.ui-panel-position-left > .ui-panel-inner {
    top: 0px;
}
```
